# Generated by Django 2.2.3 on 2019-07-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lower_percentage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('min_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('upper_percentage', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('comission_value', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Seller')),
            ],
        ),
    ]
