# Generated by Django 2.2.3 on 2019-07-19 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('seller', 'year', 'month')},
        ),
    ]
