# Generated by Django 2.2.3 on 2019-07-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190720_1443'),
        ('api', '0002_auto_20190718_2248'),
    ]

    operations = [
    ]
